version: '3.8'

name: notification-infrastructure
services:
  localstack:
    container_name: localstack
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
    environment:
      - SERVICES=sqs
      - DEFAULT_REGION=us-east-1
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - LS_LOG=info
      - LOCALSTACK_HOST=localhost
      - DEBUG=1
      - DOCKER_HOST=unix:///var/run/docker.sock
      - LOCALSTACK_AUTH_TOKEN=${AUTH_TOKEN}
    volumes:
      - ./init-aws:/etc/localstack/init/ready.d
      - ./localstack:/var/lib/localstack
  hogmail:
    image: axllent/mailpit
    container_name: hogmail
    ports:
      - "8025:8025"
      - "1025:1025"

  database:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/

volumes:
  db_data:

