version: '3.8'

name: notification-infrastructure
services:
  localstack:
    container_name: localstack
    image: localstack/localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=sqs
      - DEFAULT_REGION=us-east-1
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - LS_LOG=info
      - LOCALSTACK_HOST=localhost
      - DEBUG=1
      - DOCKER_HOST=unix:///var/run/docker.sock
      - LOCALSTACK_AUTH_TOKEN=${AUTH_TOKEN}
    volumes:
      - ./localstack:/var/lib/localstack
      - /var/run/docker.sock:/var/run/docker.sock
      - ./init-aws.sh:/etc/localstack/init/ready.d/init-aws.sh
    command: >
      sh -c "
        sleep 5 &&
        awslocal sqs create-queue --queue-name locadora-notifications || true
      "

  hogmail:
    image: axllent/mailpit
    container_name: hogmail
    ports:
      - "8025:8025"
      - "1025:1025"

  database:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root123
      POSTGRES_DB: locadora_carrosdb
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/

volumes:
  db_data:
