server.port=8090
spring.application.name=notification-consumer-service

sqs.endpoint=http://localhost:4566
sqs.queue-name=locadora-notifications

spring.main.allow-bean-definition-overriding=true

mail.host=localhost
mail.port=1025
mail.username=""
mail.password=""